## traefik.yml
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

## Dynamics File Providers
providers:
  file:
    directory: "/etc/traefik/providers.d"
    watch: true
#    docker:
#        exposedByDefault: false
#        watch: true
#        network: public
#        swarmMode: true

serversTransport:
  insecureSkipVerify: true

## Configure Metrics
# metrics:
#    prometheus:
#        buckets:
#            - 0.1
#            - 0.3
#            - 1.2
#            - 5.0
#        addEntryPointsLabels: true
#        addServicesLabels: true

## Configure Tracing

# tracing:
#    serviceName: traefik
#    spanNameLimit: 0

# tracing:
#    serviceName: traefik
#    elastic:
#        serverUrl: "http://10.10.20.200:8200"
#        serviceEnvironment: "production"

## Configure Logging
log:
  filePath: "/var/log/traefik/traefik.log"
  format: common
  level: ERROR

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep

## Backend
api:
  insecure: true

## Configure TLS/HTTPS Resolver
certificatesResolvers:
  letsencrypt:
    acme:
      caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        entryPoint: web
  staging:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        entryPoint: web
